// Re-export all types and constants from the shared module
export type {
  Priority,
  ColumnId,
  AgentStatus,
  AgentType,
  TaskLifecycleState,
  TaskLifecycleAction,
  TaskLifecycleTransition,
  TaskLifecycleTransitionContext,
  TaskLifecycleError,
  TaskLifecycleResult,
  AgentInfo,
  Project,
  ProjectTaskCounts,
  ProjectConfig,
  ProjectPathValidation,
  CreateProjectRequest,
  UpdateProjectRequest,
  Task,
  TaskAttachment,
  TaskGroup,
  TaskTemplate,
  AgentEventType,
  AgentEvent,
  Column,
  WSMessage,
} from '../../../../shared/types.js';

export {
  VALID_TRANSITIONS,
  VALID_TASK_LIFECYCLE_STATES,
  TASK_LIFECYCLE_TRANSITIONS,
  isValidTaskLifecycleState,
  getTaskLifecycleTransition,
  transitionTaskLifecycle,
  MAX_GROUP_CHILDREN,
  MIN_GROUP_CHILDREN,
} from '../../../../shared/constants.js';
