// Re-export all types and constants from the shared module
export type {
  Priority,
  ColumnId,
  AgentStatus,
  AgentType,
  AgentInfo,
  Project,
  ProjectTaskCounts,
  ProjectConfig,
  ProviderConfig,
  ProviderValidation,
  RoleBinding,
  RoleBindingOverride,
  RoleConfig,
  RoleExecutionSnapshot,
  RoleId,
  SettingsConfig,
  SettingsResponse,
  ThinkingEffort,
  ProjectPathValidation,
  CreateProjectRequest,
  UpdateProjectRequest,
  Task,
  TaskAttachment,
  TaskGroup,
  TaskTemplate,
  AgentEventType,
  AgentEvent,
  Column,
  WSMessage,
} from '../../../../shared/types.js';

export { VALID_TRANSITIONS, MAX_GROUP_CHILDREN, MIN_GROUP_CHILDREN, BUILT_IN_ROLE_IDS, VALID_THINKING_EFFORTS } from '../../../../shared/constants.js';
