// Re-export all types and validation utilities from the shared module
export type {
  Priority,
  ColumnId,
  AgentStatus,
  AgentType,
  Task,
  TaskRelationship,
  ExecutionAttempt,
  TaskProvenance,
  TaskGroup,
  TaskTemplate,
  TaskAttachment,
  Project,
  ProjectTaskCounts,
  ProjectConfig,
  ProviderConfig,
  ProviderValidation,
  RoleBinding,
  RoleBindingOverride,
  RoleConfig,
  RoleExecutionSnapshot,
  RoleId,
  SettingsConfig,
  SettingsResponse,
  ThinkingEffort,
  CreateProjectRequest,
  UpdateProjectRequest,
  AgentEvent,
  WSMessage,
} from '../../../shared/types.js';

export {
  VALID_TRANSITIONS,
  isValidPriority,
  isValidColumnId,
  isValidAgentStatus,
  isValidAgentType,
  isBuiltInRoleId,
  isValidThinkingEffort,
  MAX_GROUP_CHILDREN,
  MIN_GROUP_CHILDREN,
} from '../../../shared/constants.js';
